'use strict'

const SourceData = [
	{"code":"047","name":"Морская миля (1852 м)","conventionalNationalView":"миля","conventionalInternationalView":"n mile","symbolNationalView":"МИЛЬ","symbolInternationalView":"NMI"},
	{"code":"008","name":"Километр; тысяча метров","conventionalNationalView":"км; 10^3 м","conventionalInternationalView":"km","symbolNationalView":"КМ; ТЫС М","symbolInternationalView":"KMT"},
	{"code":"005","name":"Дециметр","conventionalNationalView":"дм","conventionalInternationalView":"dm","symbolNationalView":"ДМ","symbolInternationalView":"DMT"},
	{"code":"004","name":"Сантиметр","conventionalNationalView":"см","conventionalInternationalView":"cm","symbolNationalView":"СМ","symbolInternationalView":"CMT"},
	{"code":"039","name":"Дюйм (25,4 мм)","conventionalNationalView":"дюйм","conventionalInternationalView":"in","symbolNationalView":"ДЮЙМ","symbolInternationalView":"INH"},
	{"code":"006","name":"Метр","conventionalNationalView":"м","conventionalInternationalView":"m","symbolNationalView":"М","symbolInternationalView":"MTR"},
	{"code":"041","name":"Фут (0,3048 м)","conventionalNationalView":"фут","conventionalInternationalView":"ft","symbolNationalView":"ФУТ","symbolInternationalView":"FOT"},
	{"code":"003","name":"Миллиметр","conventionalNationalView":"мм","conventionalInternationalView":"mm","symbolNationalView":"ММ","symbolInternationalView":"MMT"},
	{"code":"009","name":"Мегаметр; миллион метров","conventionalNationalView":"Мм; 10^6 м","conventionalInternationalView":"Mm","symbolNationalView":"МЕГАМ; МЛН М","symbolInternationalView":"MAM"},
	{"code":"043","name":"Ярд (0,9144 м)","conventionalNationalView":"ярд","conventionalInternationalView":"yd","symbolNationalView":"ЯРД","symbolInternationalView":"YRD"},
	{"code":"059","name":"Гектар","conventionalNationalView":"га","conventionalInternationalView":"ha","symbolNationalView":"ГА","symbolInternationalView":"HAR"},
	{"code":"073","name":"Квадратный фут (0,092903 м2)","conventionalNationalView":"фут2","conventionalInternationalView":"ft2","symbolNationalView":"ФУТ2","symbolInternationalView":"FTK"},
	{"code":"053","name":"Квадратный дециметр","conventionalNationalView":"дм2","conventionalInternationalView":"dm2","symbolNationalView":"ДМ2","symbolInternationalView":"DMK"},
	{"code":"061","name":"Квадратный километр","conventionalNationalView":"км2","conventionalInternationalView":"km2","symbolNationalView":"КМ2","symbolInternationalView":"KMK"},
	{"code":"051","name":"Квадратный сантиметр","conventionalNationalView":"см2","conventionalInternationalView":"cm2","symbolNationalView":"СМ2","symbolInternationalView":"CMK"},
	{"code":"109","name":"Ар (100 м2)","conventionalNationalView":"а","conventionalInternationalView":"a","symbolNationalView":"АР","symbolInternationalView":"ARE"},
	{"code":"055","name":"Квадратный метр","conventionalNationalView":"м2","conventionalInternationalView":"m2","symbolNationalView":"М2","symbolInternationalView":"MTK"},
	{"code":"058","name":"Тысяча квадратных метров","conventionalNationalView":"10^3 м^2","conventionalInternationalView":"daa","symbolNationalView":"ТЫС М2","symbolInternationalView":"DAA"},
	{"code":"075","name":"Квадратный ярд (0,8361274 м2)","conventionalNationalView":"ярд2","conventionalInternationalView":"yd2","symbolNationalView":"ЯРД2","symbolInternationalView":"YDK"},
	{"code":"050","name":"Квадратный миллиметр","conventionalNationalView":"мм2","conventionalInternationalView":"mm2","symbolNationalView":"ММ2","symbolInternationalView":"MMK"},
	{"code":"071","name":"Квадратный дюйм (645,16 мм2)","conventionalNationalView":"дюйм2","conventionalInternationalView":"in2","symbolNationalView":"ДЮЙМ2","symbolInternationalView":"INK"},
	{"code":"126","name":"Мегалитр","conventionalNationalView":"Мл","conventionalInternationalView":"Ml","symbolNationalView":"МЕГАЛ","symbolInternationalView":"MAL"},
	{"code":"132","name":"Кубический фут (0,02831685 м3)","conventionalNationalView":"фут3","conventionalInternationalView":"ft3","symbolNationalView":"ФУТ3","symbolInternationalView":"FTQ"},
	{"code":"118","name":"Децилитр","conventionalNationalView":"дл","conventionalInternationalView":"dl","symbolNationalView":"ДЛ","symbolInternationalView":"DLT"},
	{"code":"133","name":"Кубический ярд (0,764555 м3)","conventionalNationalView":"ярд3","conventionalInternationalView":"yd3","symbolNationalView":"ЯРД3","symbolInternationalView":"YDQ"},
	{"code":"112","name":"Литр; кубический дециметр","conventionalNationalView":"л; дм3","conventionalInternationalView":"I; L; dm^3","symbolNationalView":"Л; ДМ3","symbolInternationalView":"LTR; DMQ"},
	{"code":"113","name":"Кубический метр","conventionalNationalView":"м3","conventionalInternationalView":"m3","symbolNationalView":"М3","symbolInternationalView":"MTQ"},
	{"code":"131","name":"Кубический дюйм (16387,1 мм3)","conventionalNationalView":"дюйм3","conventionalInternationalView":"in3","symbolNationalView":"ДЮЙМ3","symbolInternationalView":"INQ"},
	{"code":"159","name":"Миллион кубических метров","conventionalNationalView":"10^6 м3","conventionalInternationalView":"10^6 m3","symbolNationalView":"МЛН М3","symbolInternationalView":"HMQ"},
	{"code":"110","name":"Кубический миллиметр","conventionalNationalView":"мм3","conventionalInternationalView":"mm3","symbolNationalView":"ММ3","symbolInternationalView":"MMQ"},
	{"code":"122","name":"Гектолитр","conventionalNationalView":"гл","conventionalInternationalView":"hl","symbolNationalView":"ГЛ","symbolInternationalView":"HLT"},
	{"code":"111","name":"Кубический сантиметр; миллилитр","conventionalNationalView":"см3; мл","conventionalInternationalView":"cm3; ml","symbolNationalView":"СМ3; МЛ","symbolInternationalView":"CMQ; MLT"},
	{"code":"170","name":"Килотонна","conventionalNationalView":"10^3 т","conventionalInternationalView":"kt","symbolNationalView":"КТ","symbolInternationalView":"KTN"},
	{"code":"161","name":"Миллиграмм","conventionalNationalView":"мг","conventionalInternationalView":"mg","symbolNationalView":"МГ","symbolInternationalView":"MGM"},
	{"code":"173","name":"Сантиграмм","conventionalNationalView":"сг","conventionalInternationalView":"cg","symbolNationalView":"СГ","symbolInternationalView":"CGM"},
	{"code":"206","name":"Центнер (метрический) (100 кг); гектокилограмм; квинтал1 (метрический); децитонна","conventionalNationalView":"ц","conventionalInternationalView":"q; 10^2 kg","symbolNationalView":"Ц","symbolInternationalView":"DTN"},
	{"code":"163","name":"Грамм","conventionalNationalView":"г","conventionalInternationalView":"g","symbolNationalView":"Г","symbolInternationalView":"GRM"},
	{"code":"181","name":"Брутто-регистровая тонна (2,8316 м3)","conventionalNationalView":"БРТ","conventionalInternationalView":"","symbolNationalView":"БРУТТ. РЕГИСТР Т","symbolInternationalView":"GRT"},
	{"code":"160","name":"Гектограмм","conventionalNationalView":"гг","conventionalInternationalView":"hg","symbolNationalView":"ГГ","symbolInternationalView":"HGM"},
	{"code":"168","name":"Тонна; метрическая тонна (1000 кг)","conventionalNationalView":"т","conventionalInternationalView":"t","symbolNationalView":"Т","symbolInternationalView":"TNE"},
	{"code":"162","name":"Метрический карат","conventionalNationalView":"кар","conventionalInternationalView":"МС","symbolNationalView":"КАР","symbolInternationalView":"CTM"},
	{"code":"185","name":"Грузоподъемность в метрических тоннах","conventionalNationalView":"т грп","conventionalInternationalView":"","symbolNationalView":"Т ГРУЗОПОД","symbolInternationalView":"CCT"},
	{"code":"166","name":"Килограмм","conventionalNationalView":"кг","conventionalInternationalView":"kg","symbolNationalView":"КГ","symbolInternationalView":"KGM"},
	{"code":"331","name":"Оборот в минуту","conventionalNationalView":"об/мин","conventionalInternationalView":"r/min","symbolNationalView":"ОБ/МИН","symbolInternationalView":"RPM"},
	{"code":"300","name":"Физическая атмосфера (101325 Па)","conventionalNationalView":"атм","conventionalInternationalView":"atm","symbolNationalView":"АТМ","symbolInternationalView":"ATM"},
	{"code":"306","name":"Грамм делящихся изотопов","conventionalNationalView":"г Д/И","conventionalInternationalView":"g fissile isotopes","symbolNationalView":"Г ДЕЛЯЩ ИЗОТОП","symbolInternationalView":"GFI"},
	{"code":"304","name":"Милликюри","conventionalNationalView":"мКи","conventionalInternationalView":"mCi","symbolNationalView":"МКИ","symbolInternationalView":"MCU"},
	{"code":"243","name":"Ватт-час","conventionalNationalView":"Вт.ч","conventionalInternationalView":"W.h","symbolNationalView":"ВТ.Ч","symbolInternationalView":"WHR"},
	{"code":"309","name":"Бар","conventionalNationalView":"бар","conventionalInternationalView":"bar","symbolNationalView":"БАР","symbolInternationalView":"BAR"},
	{"code":"301","name":"Техническая атмосфера (98066,5 Па)","conventionalNationalView":"ат","conventionalInternationalView":"at","symbolNationalView":"АТТ","symbolInternationalView":"ATT"},
	{"code":"270","name":"Кулон","conventionalNationalView":"Кл","conventionalInternationalView":"C","symbolNationalView":"КЛ","symbolInternationalView":"COU"},
	{"code":"288","name":"Кельвин","conventionalNationalView":"K","conventionalInternationalView":"K","symbolNationalView":"К","symbolInternationalView":"KEL"},
	{"code":"280","name":"Градус Цельсия","conventionalNationalView":"град. C","conventionalInternationalView":"град. C","symbolNationalView":"ГРАД ЦЕЛЬС","symbolInternationalView":"CEL"},
	{"code":"282","name":"Кандела","conventionalNationalView":"кд","conventionalInternationalView":"cd","symbolNationalView":"КД","symbolInternationalView":"CDL"},
	{"code":"330","name":"Оборот в секунду","conventionalNationalView":"об/с","conventionalInternationalView":"r/s","symbolNationalView":"ОБ/С","symbolInternationalView":"RPS"},
	{"code":"297","name":"Килопаскаль","conventionalNationalView":"кПа","conventionalInternationalView":"kPa","symbolNationalView":"КПА","symbolInternationalView":"KPA"},
	{"code":"302","name":"Гигабеккерель","conventionalNationalView":"ГБк","conventionalInternationalView":"GBq","symbolNationalView":"ГИГАБК","symbolInternationalView":"GBQ"},
	{"code":"291","name":"Килогерц","conventionalNationalView":"кГц","conventionalInternationalView":"kHz","symbolNationalView":"КГЦ","symbolInternationalView":"KHZ"},
	{"code":"230","name":"Киловар","conventionalNationalView":"квар","conventionalInternationalView":"kVAR","symbolNationalView":"КВАР","symbolInternationalView":"KVR"},
	{"code":"281","name":"Градус Фаренгейта","conventionalNationalView":"град. F","conventionalInternationalView":"град. F","symbolNationalView":"ГРАД ФАРЕНГ","symbolInternationalView":"FAN"},
	{"code":"292","name":"Мегагерц","conventionalNationalView":"МГц","conventionalInternationalView":"MHz","symbolNationalView":"МЕГАГЦ","symbolInternationalView":"MHZ"},
	{"code":"227","name":"Киловольт-ампер","conventionalNationalView":"кВ.А","conventionalInternationalView":"kV.A","symbolNationalView":"КВ.А","symbolInternationalView":"KVA"},
	{"code":"323","name":"Беккерель","conventionalNationalView":"Бк","conventionalInternationalView":"Bq","symbolNationalView":"БК","symbolInternationalView":"BQL"},
	{"code":"298","name":"Мегапаскаль","conventionalNationalView":"МПа","conventionalInternationalView":"MPa","symbolNationalView":"МЕГАПА","symbolInternationalView":"MPA"},
	{"code":"263","name":"Ампер-час (3,6 кКл)","conventionalNationalView":"А.ч","conventionalInternationalView":"A.h","symbolNationalView":"А.Ч","symbolInternationalView":"AMH"},
	{"code":"247","name":"Гигаватт-час (миллион киловатт-часов)","conventionalNationalView":"ГВт.ч","conventionalInternationalView":"GW.h","symbolNationalView":"ГИГАВТ.Ч","symbolInternationalView":"GWH"},
	{"code":"245","name":"Киловатт-час","conventionalNationalView":"кВт.ч","conventionalInternationalView":"kW.h","symbolNationalView":"КВТ.Ч","symbolInternationalView":"KWH"},
	{"code":"212","name":"Ватт","conventionalNationalView":"Вт","conventionalInternationalView":"W","symbolNationalView":"ВТ","symbolInternationalView":"WTT"},
	{"code":"273","name":"Килоджоуль","conventionalNationalView":"кДж","conventionalInternationalView":"kJ","symbolNationalView":"КДЖ","symbolInternationalView":"KJO"},
	{"code":"305","name":"Кюри","conventionalNationalView":"Ки","conventionalInternationalView":"Ci","symbolNationalView":"КИ","symbolInternationalView":"CUR"},
	{"code":"228","name":"Мегавольт-ампер (тысяча киловольт-ампер)","conventionalNationalView":"МВ.А","conventionalInternationalView":"MV.A","symbolNationalView":"МЕГАВ.А","symbolInternationalView":"MVA"},
	{"code":"314","name":"Фарад","conventionalNationalView":"Ф","conventionalInternationalView":"F","symbolNationalView":"Ф","symbolInternationalView":"FAR"},
	{"code":"284","name":"Люмен","conventionalNationalView":"лм","conventionalInternationalView":"lm","symbolNationalView":"ЛМ","symbolInternationalView":"LUM"},
	{"code":"215","name":"Мегаватт; тысяча киловатт","conventionalNationalView":"МВт; 10^3 кВт","conventionalInternationalView":"MW","symbolNationalView":"МЕГАВТ; ТЫС КВТ","symbolInternationalView":"MAW"},
	{"code":"274","name":"Ом","conventionalNationalView":"Ом","conventionalInternationalView":"<омега>","symbolNationalView":"ОМ","symbolInternationalView":"OHM"},
	{"code":"271","name":"Джоуль","conventionalNationalView":"Дж","conventionalInternationalView":"J","symbolNationalView":"ДЖ","symbolInternationalView":"JOU"},
	{"code":"333","name":"Километр в час","conventionalNationalView":"км/ч","conventionalInternationalView":"km/h","symbolNationalView":"КМ/Ч","symbolInternationalView":"KMH"},
	{"code":"349","name":"Кулон на килограмм","conventionalNationalView":"Кл/кг","conventionalInternationalView":"C/kg","symbolNationalView":"КЛ/КГ","symbolInternationalView":"CKG"},
	{"code":"264","name":"Тысяча ампер-часов","conventionalNationalView":"10^3 А.ч","conventionalInternationalView":"10^3 A.h","symbolNationalView":"ТЫС А.Ч","symbolInternationalView":"TAH"},
	{"code":"222","name":"Вольт","conventionalNationalView":"В","conventionalInternationalView":"V","symbolNationalView":"В","symbolInternationalView":"VLT"},
	{"code":"223","name":"Киловольт","conventionalNationalView":"кВ","conventionalInternationalView":"kV","symbolNationalView":"КВ","symbolInternationalView":"KVT"},
	{"code":"335","name":"Метр на секунду в квадрате","conventionalNationalView":"м/с2","conventionalInternationalView":"m/s2","symbolNationalView":"М/С2","symbolInternationalView":"MSK"},
	{"code":"290","name":"Герц","conventionalNationalView":"Гц","conventionalInternationalView":"Hz","symbolNationalView":"ГЦ","symbolInternationalView":"HTZ"},
	{"code":"260","name":"Ампер","conventionalNationalView":"А","conventionalInternationalView":"A","symbolNationalView":"А","symbolInternationalView":"AMP"},
	{"code":"246","name":"Мегаватт-час; 1000 киловатт-часов","conventionalNationalView":"МВт.ч; 10^3 кВт.ч","conventionalInternationalView":"МW.h","symbolNationalView":"МЕГАВТ.Ч; ТЫС КВТ.Ч","symbolInternationalView":"MWH"},
	{"code":"324","name":"Вебер","conventionalNationalView":"Вб","conventionalInternationalView":"Wb","symbolNationalView":"ВБ","symbolInternationalView":"WEB"},
	{"code":"312","name":"Килобар","conventionalNationalView":"кб","conventionalInternationalView":"kbar","symbolNationalView":"КБАР","symbolInternationalView":"KBA"},
	{"code":"294","name":"Паскаль","conventionalNationalView":"Па","conventionalInternationalView":"Pa","symbolNationalView":"ПА","symbolInternationalView":"PAL"},
	{"code":"283","name":"Люкс","conventionalNationalView":"лк","conventionalInternationalView":"lx","symbolNationalView":"ЛК","symbolInternationalView":"LUX"},
	{"code":"310","name":"Гектобар","conventionalNationalView":"гб","conventionalInternationalView":"hbar","symbolNationalView":"ГБАР","symbolInternationalView":"HBA"},
	{"code":"308","name":"Миллибар","conventionalNationalView":"мб","conventionalInternationalView":"mbar","symbolNationalView":"МБАР","symbolInternationalView":"MBR"},
	{"code":"327","name":"Узел (миля/ч)","conventionalNationalView":"уз","conventionalInternationalView":"kn","symbolNationalView":"УЗ","symbolInternationalView":"KNT"},
	{"code":"296","name":"Сименс","conventionalNationalView":"См","conventionalInternationalView":"S","symbolNationalView":"СИ","symbolInternationalView":"SIE"},
	{"code":"316","name":"Килограмм на кубический метр","conventionalNationalView":"кг/м3","conventionalInternationalView":"kg/m3","symbolNationalView":"КГ/М3","symbolInternationalView":"KMQ"},
	{"code":"328","name":"Метр в секунду","conventionalNationalView":"м/с","conventionalInternationalView":"m/s","symbolNationalView":"М/С","symbolInternationalView":"MTS"},
	{"code":"214","name":"Киловатт","conventionalNationalView":"кВт","conventionalInternationalView":"kW","symbolNationalView":"КВТ","symbolInternationalView":"KWT"},
	{"code":"289","name":"Ньютон","conventionalNationalView":"Н","conventionalInternationalView":"N","symbolNationalView":"Н","symbolInternationalView":"NEW"},
	{"code":"368","name":"Десятилетие","conventionalNationalView":"деслет","conventionalInternationalView":"","symbolNationalView":"ДЕСЛЕТ","symbolInternationalView":"DEC"},
	{"code":"361","name":"Декада","conventionalNationalView":"дек","conventionalInternationalView":"","symbolNationalView":"ДЕК","symbolInternationalView":"DAD"},
	{"code":"364","name":"Квартал","conventionalNationalView":"кварт","conventionalInternationalView":"","symbolNationalView":"КВАРТ","symbolInternationalView":"QAN"},
	{"code":"365","name":"Полугодие","conventionalNationalView":"полгода","conventionalInternationalView":"","symbolNationalView":"ПОЛГОД","symbolInternationalView":"SAN"},
	{"code":"362","name":"Месяц","conventionalNationalView":"мес","conventionalInternationalView":"","symbolNationalView":"МЕС","symbolInternationalView":"MON"},
	{"code":"359","name":"Сутки","conventionalNationalView":"сут; дн","conventionalInternationalView":"d","symbolNationalView":"СУТ; ДН","symbolInternationalView":"DAY"},
	{"code":"355","name":"Минута","conventionalNationalView":"мин","conventionalInternationalView":"min","symbolNationalView":"МИН","symbolInternationalView":"MIN"},
	{"code":"356","name":"Час","conventionalNationalView":"ч","conventionalInternationalView":"h","symbolNationalView":"Ч","symbolInternationalView":"HUR"},
	{"code":"360","name":"Неделя","conventionalNationalView":"нед","conventionalInternationalView":"","symbolNationalView":"НЕД","symbolInternationalView":"WEE"},
	{"code":"354","name":"Секунда","conventionalNationalView":"с","conventionalInternationalView":"s","symbolNationalView":"С","symbolInternationalView":"SEC"},
	{"code":"366","name":"Год","conventionalNationalView":"г; лет","conventionalInternationalView":"a","symbolNationalView":"ГОД; ЛЕТ","symbolInternationalView":"ANN"},
	{"code":"745","name":"Элемент","conventionalNationalView":"элем","conventionalInternationalView":"CI","symbolNationalView":"ЭЛЕМ","symbolInternationalView":"NCL"},
	{"code":"781","name":"Сто упаковок","conventionalNationalView":"100 упак","conventionalInternationalView":"","symbolNationalView":"100 УПАК","symbolInternationalView":"CNP"},
	{"code":"732","name":"Десять пар","conventionalNationalView":"10 пар","conventionalInternationalView":"","symbolNationalView":"ДЕС ПАР","symbolInternationalView":"TPR"},
	{"code":"599","name":"Тысяча кубических метров в сутки","conventionalNationalView":"10^3 м3/сут","conventionalInternationalView":"","symbolNationalView":"ТЫС М3/СУТ","symbolInternationalView":"TQD"},
	{"code":"730","name":"Два десятка","conventionalNationalView":"20","conventionalInternationalView":"20","symbolNationalView":"2 ДЕС","symbolInternationalView":"SCO"},
	{"code":"733","name":"Дюжина пар","conventionalNationalView":"дюжина пар","conventionalInternationalView":"","symbolNationalView":"ДЮЖИНА ПАР","symbolInternationalView":"DPR"},
	{"code":"799","name":"Миллион штук","conventionalNationalView":"10^6 шт","conventionalInternationalView":"10^6","symbolNationalView":"МЛН ШТ","symbolInternationalView":"MIO"},
	{"code":"796","name":"Штука","conventionalNationalView":"шт","conventionalInternationalView":"pc; 1","symbolNationalView":"ШТ","symbolInternationalView":"PCE; NMB"},
	{"code":"778","name":"Упаковка","conventionalNationalView":"упак","conventionalInternationalView":"","symbolNationalView":"УПАК","symbolInternationalView":"NMP"},
	{"code":"831","name":"Литр чистого (100%) спирта","conventionalNationalView":"л 100% спирта","conventionalInternationalView":"","symbolNationalView":"Л ЧИСТ СПИРТ","symbolInternationalView":"LPA"},
	{"code":"657","name":"Изделие","conventionalNationalView":"изд","conventionalInternationalView":"","symbolNationalView":"ИЗД","symbolInternationalView":"NAR"},
	{"code":"865","name":"Килограмм пятиокиси фосфора","conventionalNationalView":"кг Р2О5","conventionalInternationalView":"","symbolNationalView":"КГ ПЯТИОКИСЬ ФОСФОРА","symbolInternationalView":"KPP"},
	{"code":"641","name":"Дюжина (12 шт.)","conventionalNationalView":"дюжина","conventionalInternationalView":"Doz; 12","symbolNationalView":"ДЮЖИНА","symbolInternationalView":"DZN"},
	{"code":"841","name":"Килограмм пероксида водорода","conventionalNationalView":"кг H2О2","conventionalInternationalView":"","symbolNationalView":"КГ ПЕРОКСИД ВОДОРОДА","symbolInternationalView":""},
	{"code":"734","name":"Посылка","conventionalNationalView":"посыл","conventionalInternationalView":"","symbolNationalView":"ПОСЫЛ","symbolInternationalView":"NPL"},
	{"code":"704","name":"Набор","conventionalNationalView":"набор","conventionalInternationalView":"","symbolNationalView":"НАБОР","symbolInternationalView":"SET"},
	{"code":"847","name":"Тонна 90%-го сухого вещества","conventionalNationalView":"т 90% с/в","conventionalInternationalView":"","symbolNationalView":"Т 90 ПРОЦ СУХ ВЕЩ","symbolInternationalView":"TSD"},
	{"code":"499","name":"Килограмм в секунду","conventionalNationalView":"кг/с","conventionalInternationalView":"","symbolNationalView":"КГ/С","symbolInternationalView":"KGS"},
	{"code":"801","name":"Биллион штук (Европа); триллион штук","conventionalNationalView":"10^12 шт","conventionalInternationalView":"10^12","symbolNationalView":"БИЛЛ ШТ (ЕВР); ТРИЛЛ ШТ","symbolInternationalView":"BIL"},
	{"code":"683","name":"Сто ящиков","conventionalNationalView":"100 ящ.","conventionalInternationalView":"Hbx","symbolNationalView":"100 ЯЩ","symbolInternationalView":"HBX"},
	{"code":"740","name":"Дюжина штук","conventionalNationalView":"дюжина шт","conventionalInternationalView":"","symbolNationalView":"ДЮЖИНА ШТ","symbolInternationalView":"DPC"},
	{"code":"802","name":"Квинтильон штук (Европа)","conventionalNationalView":"10^18 шт","conventionalInternationalView":"10^18","symbolNationalView":"КВИНТ ШТ","symbolInternationalView":"TRL"},
	{"code":"821","name":"Крепость спирта по объему","conventionalNationalView":"креп. спирта по объему","conventionalInternationalView":"% vol","symbolNationalView":"КРЕП СПИРТ ПО ОБЪЕМ","symbolInternationalView":"ASV"},
	{"code":"533","name":"Тонна пара в час","conventionalNationalView":"т пар/ч","conventionalInternationalView":"","symbolNationalView":"Т ПАР/Ч","symbolInternationalView":"TSH"},
	{"code":"859","name":"Килограмм гидроксида калия","conventionalNationalView":"кг КОН","conventionalInternationalView":"","symbolNationalView":"КГ ГИДРОКСИД КАЛИЯ","symbolInternationalView":"KPH"},
	{"code":"852","name":"Килограмм оксида калия","conventionalNationalView":"кг К2О","conventionalInternationalView":"","symbolNationalView":"КГ ОКСИД КАЛИЯ","symbolInternationalView":"KPO"},
	{"code":"625","name":"Лист","conventionalNationalView":"л.","conventionalInternationalView":"","symbolNationalView":"ЛИСТ","symbolInternationalView":"LEF"},
	{"code":"798","name":"Тысяча штук","conventionalNationalView":"тыс. шт; 1000 шт","conventionalInternationalView":"1000","symbolNationalView":"ТЫС ШТ","symbolInternationalView":"MIL"},
	{"code":"630","name":"Тысяча стандартных условных кирпичей","conventionalNationalView":"тыс станд. усл. кирп","conventionalInternationalView":"","symbolNationalView":"ТЫС СТАНД УСЛ КИРП","symbolInternationalView":"MBE"},
	{"code":"797","name":"Сто штук","conventionalNationalView":"100 шт","conventionalInternationalView":"100","symbolNationalView":"100 ШТ","symbolInternationalView":"CEN"},
	{"code":"626","name":"Сто листов","conventionalNationalView":"100 л.","conventionalInternationalView":"","symbolNationalView":"100 ЛИСТ","symbolInternationalView":"CLF"},
	{"code":"736","name":"Рулон","conventionalNationalView":"рул","conventionalInternationalView":"","symbolNationalView":"РУЛ","symbolInternationalView":"NPL"},
	{"code":"780","name":"Дюжина упаковок","conventionalNationalView":"дюжина упак","conventionalInternationalView":"","symbolNationalView":"ДЮЖИНА УПАК","symbolInternationalView":"DZP"},
	{"code":"800","name":"Миллиард штук","conventionalNationalView":"10^9 шт","conventionalInternationalView":"10^9","symbolNationalView":"МЛРД ШТ","symbolInternationalView":"MLD"},
	{"code":"863","name":"Килограмм гидроксида натрия","conventionalNationalView":"кг NaOH","conventionalInternationalView":"","symbolNationalView":"КГ ГИДРОКСИД НАТРИЯ","symbolInternationalView":"KSH"},
	{"code":"833","name":"Гектолитр чистого (100%) спирта","conventionalNationalView":"Гл 100% спирта","conventionalInternationalView":"","symbolNationalView":"ГЛ ЧИСТ СПИРТ","symbolInternationalView":"HPA"},
	{"code":"715","name":"Пара (2 шт.)","conventionalNationalView":"пар","conventionalInternationalView":"pr; 2","symbolNationalView":"ПАР","symbolInternationalView":"NPR"},
	{"code":"861","name":"Килограмм азота","conventionalNationalView":"кг N","conventionalInternationalView":"","symbolNationalView":"КГ АЗОТ","symbolInternationalView":"KNI"},
	{"code":"598","name":"Кубический метр в час","conventionalNationalView":"м3/ч","conventionalInternationalView":"m3/h","symbolNationalView":"М3/Ч","symbolInternationalView":"MQH"},
	{"code":"845","name":"Килограмм 90%-го сухого вещества","conventionalNationalView":"кг 90% с/в","conventionalInternationalView":"","symbolNationalView":"КГ 90 ПРОЦ СУХ ВЕЩ","symbolInternationalView":"KSD"},
	{"code":"867","name":"Килограмм урана","conventionalNationalView":"кг U","conventionalInternationalView":"","symbolNationalView":"КГ УРАН","symbolInternationalView":"KUR"},
	{"code":"735","name":"Часть","conventionalNationalView":"часть","conventionalInternationalView":"","symbolNationalView":"ЧАСТЬ","symbolInternationalView":"NPT"},
	{"code":"820","name":"Крепость спирта по массе","conventionalNationalView":"креп. спирта по массе","conventionalInternationalView":"% mds","symbolNationalView":"КРЕП СПИРТ ПО МАССЕ","symbolInternationalView":"ASM"},
	{"code":"737","name":"Дюжина рулонов","conventionalNationalView":"дюжина рул","conventionalInternationalView":"","symbolNationalView":"ДЮЖИНА РУЛ","symbolInternationalView":"DRL"},
	{"code":"616","name":"Бобина","conventionalNationalView":"боб","conventionalInternationalView":"","symbolNationalView":"БОБ","symbolInternationalView":"NBB"},
	{"code":"596","name":"Кубический метр в секунду","conventionalNationalView":"м3/с","conventionalInternationalView":"m3/s","symbolNationalView":"М3/С","symbolInternationalView":"MQS"},
	{"code":"049","name":"Километр условных труб","conventionalNationalView":"км усл. труб","conventionalInternationalView":"","symbolNationalView":"КМ УСЛ ТРУБ","symbolInternationalView":""},
	{"code":"020","name":"Условный метр","conventionalNationalView":"усл. м","conventionalInternationalView":"","symbolNationalView":"УСЛ М","symbolInternationalView":""},
	{"code":"048","name":"Тысяча условных метров","conventionalNationalView":"10^3 усл. м","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ М","symbolInternationalView":""},
	{"code":"018","name":"Погонный метр","conventionalNationalView":"пог. м","conventionalInternationalView":"","symbolNationalView":"ПОГ М","symbolInternationalView":""},
	{"code":"019","name":"Тысяча погонных метров","conventionalNationalView":"10^3 пог. м","conventionalInternationalView":"","symbolNationalView":"ТЫС ПОГ М","symbolInternationalView":""},
	{"code":"057","name":"Миллион квадратных метров","conventionalNationalView":"10^6 м2","conventionalInternationalView":"","symbolNationalView":"МЛН М2","symbolInternationalView":""},
	{"code":"081","name":"Квадратный метр общей площади","conventionalNationalView":"м2 общ. пл","conventionalInternationalView":"","symbolNationalView":"М2 ОБЩ ПЛ","symbolInternationalView":""},
	{"code":"064","name":"Миллион условных квадратных метров","conventionalNationalView":"10^6 усл. м2","conventionalInternationalView":"","symbolNationalView":"МЛН УСЛ М2","symbolInternationalView":""},
	{"code":"083","name":"Миллион квадратных метров общей площади","conventionalNationalView":"10^6 м2 общ. пл","conventionalInternationalView":"","symbolNationalView":"МЛН М2. ОБЩ ПЛ","symbolInternationalView":""},
	{"code":"062","name":"Условный квадратный метр","conventionalNationalView":"усл. м2","conventionalInternationalView":"","symbolNationalView":"УСЛ М2","symbolInternationalView":""},
	{"code":"063","name":"Тысяча условных квадратных метров","conventionalNationalView":"10^3 усл. м2","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ М2","symbolInternationalView":""},
	{"code":"086","name":"Миллион квадратных метров жилой площади","conventionalNationalView":"10^6 м2 жил. пл","conventionalInternationalView":"","symbolNationalView":"МЛН М2 ЖИЛ ПЛ","symbolInternationalView":""},
	{"code":"082","name":"Тысяча квадратных метров общей площади","conventionalNationalView":"10^3 м2 общ. пл","conventionalInternationalView":"","symbolNationalView":"ТЫС М2 ОБЩ ПЛ","symbolInternationalView":""},
	{"code":"056","name":"Миллион квадратных дециметров","conventionalNationalView":"10^6 дм2","conventionalInternationalView":"","symbolNationalView":"МЛН ДМ2","symbolInternationalView":""},
	{"code":"054","name":"Тысяча квадратных дециметров","conventionalNationalView":"10^3 дм2","conventionalInternationalView":"","symbolNationalView":"ТЫС ДМ2","symbolInternationalView":""},
	{"code":"089","name":"Миллион квадратных метров в двухмиллиметровом исчислении","conventionalNationalView":"10^6 м2 2 мм исч","conventionalInternationalView":"","symbolNationalView":"МЛН М2 2ММ ИСЧ","symbolInternationalView":""},
	{"code":"060","name":"Тысяча гектаров","conventionalNationalView":"10^3 га","conventionalInternationalView":"","symbolNationalView":"ТЫС ГА","symbolInternationalView":""},
	{"code":"088","name":"Тысяча квадратных метров учебно-лабораторных зданий","conventionalNationalView":"10^3 м2 уч. лаб. здан","conventionalInternationalView":"","symbolNationalView":"ТЫС М2 УЧ. ЛАБ ЗДАН","symbolInternationalView":""},
	{"code":"087","name":"Квадратный метр учебно-лабораторных зданий","conventionalNationalView":"м2 уч. лаб. здан","conventionalInternationalView":"","symbolNationalView":"М2 УЧ.ЛАБ ЗДАН","symbolInternationalView":""},
	{"code":"085","name":"Тысяча квадратных метров жилой площади","conventionalNationalView":"10^3 м2 жил. пл","conventionalInternationalView":"","symbolNationalView":"ТЫС М2 ЖИЛ ПЛ","symbolInternationalView":""},
	{"code":"084","name":"Квадратный метр жилой площади","conventionalNationalView":"м2 жил. пл","conventionalInternationalView":"","symbolNationalView":"М2 ЖИЛ ПЛ","symbolInternationalView":""},
	{"code":"121","name":"Плотный кубический метр","conventionalNationalView":"плотн. м3","conventionalInternationalView":"","symbolNationalView":"ПЛОТН М3","symbolInternationalView":""},
	{"code":"124","name":"Тысяча условных кубических метров","conventionalNationalView":"10^3 усл. м3","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ М3","symbolInternationalView":""},
	{"code":"130","name":"Тысяча литров; 1000 литров","conventionalNationalView":"10^3 л; 1000 л","conventionalInternationalView":"","symbolNationalView":"ТЫС Л","symbolInternationalView":""},
	{"code":"120","name":"Миллион декалитров","conventionalNationalView":"10^6 дкл","conventionalInternationalView":"","symbolNationalView":"МЛН ДКЛ","symbolInternationalView":""},
	{"code":"129","name":"Миллион полулитров","conventionalNationalView":"10^6 пол. л","conventionalInternationalView":"","symbolNationalView":"МЛН ПОЛ Л","symbolInternationalView":""},
	{"code":"128","name":"Тысяча полулитров","conventionalNationalView":"10^3 пол. л","conventionalInternationalView":"","symbolNationalView":"ТЫС ПОЛ Л","symbolInternationalView":""},
	{"code":"123","name":"Условный кубический метр","conventionalNationalView":"усл. м3","conventionalInternationalView":"","symbolNationalView":"УСЛ М3","symbolInternationalView":""},
	{"code":"127","name":"Тысяча плотных кубических метров","conventionalNationalView":"10^3 плотн. м3","conventionalInternationalView":"","symbolNationalView":"ТЫС ПЛОТН М3","symbolInternationalView":""},
	{"code":"116","name":"Декалитр","conventionalNationalView":"дкл","conventionalInternationalView":"","symbolNationalView":"ДКЛ","symbolInternationalView":""},
	{"code":"114","name":"Тысяча кубических метров","conventionalNationalView":"10^3 м3","conventionalInternationalView":"","symbolNationalView":"ТЫС М3","symbolInternationalView":""},
	{"code":"115","name":"Миллиард кубических метров","conventionalNationalView":"10^9 м3","conventionalInternationalView":"","symbolNationalView":"МЛРД М3","symbolInternationalView":""},
	{"code":"119","name":"Тысяча декалитров","conventionalNationalView":"10^3 дкл","conventionalInternationalView":"","symbolNationalView":"ТЫС ДКЛ","symbolInternationalView":""},
	{"code":"125","name":"Миллион кубических метров переработки газа","conventionalNationalView":"10^6 м3 перераб. газа","conventionalInternationalView":"","symbolNationalView":"МЛН М3 ПЕРЕРАБ ГАЗА","symbolInternationalView":""},
	{"code":"167","name":"Миллион каратов метрических","conventionalNationalView":"10^6 кар","conventionalInternationalView":"","symbolNationalView":"МЛН КАР","symbolInternationalView":""},
	{"code":"178","name":"Тысяча тонн переработки","conventionalNationalView":"10^3 т перераб","conventionalInternationalView":"","symbolNationalView":"ТЫС Т ПЕРЕРАБ","symbolInternationalView":""},
	{"code":"176","name":"Миллион тонн условного топлива","conventionalNationalView":"10^6 т усл. топл","conventionalInternationalView":"","symbolNationalView":"МЛН Т УСЛ ТОПЛ","symbolInternationalView":""},
	{"code":"179","name":"Условная тонна","conventionalNationalView":"усл. т","conventionalInternationalView":"","symbolNationalView":"УСЛ Т","symbolInternationalView":""},
	{"code":"207","name":"Тысяча центнеров","conventionalNationalView":"10^3 ц","conventionalInternationalView":"","symbolNationalView":"ТЫС Ц","symbolInternationalView":""},
	{"code":"171","name":"Миллион тонн","conventionalNationalView":"10^6 т","conventionalInternationalView":"","symbolNationalView":"МЛН Т","symbolInternationalView":""},
	{"code":"177","name":"Тысяча тонн единовременного хранения","conventionalNationalView":"10^3 т единовр. хран","conventionalInternationalView":"","symbolNationalView":"ТЫС Т ЕДИНОВР ХРАН","symbolInternationalView":""},
	{"code":"169","name":"Тысяча тонн","conventionalNationalView":"10^3 т","conventionalInternationalView":"","symbolNationalView":"ТЫС Т","symbolInternationalView":""},
	{"code":"165","name":"Тысяча каратов метрических","conventionalNationalView":"10^3 кар","conventionalInternationalView":"","symbolNationalView":"ТЫС КАР","symbolInternationalView":""},
	{"code":"175","name":"Тысяча тонн условного топлива","conventionalNationalView":"10^3 т усл. топл","conventionalInternationalView":"","symbolNationalView":"ТЫС Т УСЛ ТОПЛ","symbolInternationalView":""},
	{"code":"172","name":"Тонна условного топлива","conventionalNationalView":"т усл. топл","conventionalInternationalView":"","symbolNationalView":"Т УСЛ ТОПЛ","symbolInternationalView":""},
	{"code":"226","name":"Вольт-ампер","conventionalNationalView":"В.А","conventionalInternationalView":"","symbolNationalView":"В.А","symbolInternationalView":""},
	{"code":"339","name":"Сантиметр водяного столба","conventionalNationalView":"см вод. ст","conventionalInternationalView":"","symbolNationalView":"СМ ВОД СТ","symbolInternationalView":""},
	{"code":"236","name":"Калория в час","conventionalNationalView":"кал/ч","conventionalInternationalView":"","symbolNationalView":"КАЛ/Ч","symbolInternationalView":""},
	{"code":"255","name":"Байт","conventionalNationalView":"бай","conventionalInternationalView":"","symbolNationalView":"БАЙТ","symbolInternationalView":""},
	{"code":"287","name":"Генри","conventionalNationalView":"Гн","conventionalInternationalView":"","symbolNationalView":"ГН","symbolInternationalView":""},
	{"code":"250","name":"Тысяча киловольт-ампер реактивных","conventionalNationalView":"10^3 кВ.А Р","conventionalInternationalView":"","symbolNationalView":"ТЫС КВ.А Р","symbolInternationalView":""},
	{"code":"235","name":"Миллион гигакалорий","conventionalNationalView":"10^6 Гкал","conventionalInternationalView":"","symbolNationalView":"МЛН ГИГАКАЛ","symbolInternationalView":""},
	{"code":"313","name":"Тесла","conventionalNationalView":"Тл","conventionalInternationalView":"","symbolNationalView":"ТЛ","symbolInternationalView":""},
	{"code":"256","name":"Килобайт","conventionalNationalView":"кбайт","conventionalInternationalView":"","symbolNationalView":"КБАЙТ","symbolInternationalView":""},
	{"code":"234","name":"Тысяча гигакалорий","conventionalNationalView":"10^3 Гкал","conventionalInternationalView":"","symbolNationalView":"ТЫС ГИГАКАЛ","symbolInternationalView":""},
	{"code":"237","name":"Килокалория в час","conventionalNationalView":"ккал/ч","conventionalInternationalView":"","symbolNationalView":"ККАЛ/Ч","symbolInternationalView":""},
	{"code":"239","name":"Тысяча гигакалорий в час","conventionalNationalView":"10^3 Гкал/ч","conventionalInternationalView":"","symbolNationalView":"ТЫС ГИГАКАЛ/Ч","symbolInternationalView":""},
	{"code":"317","name":"Килограмм на квадратный сантиметр","conventionalNationalView":"кг/см^2","conventionalInternationalView":"","symbolNationalView":"КГ/СМ2","symbolInternationalView":""},
	{"code":"252","name":"Тысяча лошадиных сил","conventionalNationalView":"10^3 л. с","conventionalInternationalView":"","symbolNationalView":"ТЫС ЛС","symbolInternationalView":""},
	{"code":"238","name":"Гигакалория в час","conventionalNationalView":"Гкал/ч","conventionalInternationalView":"","symbolNationalView":"ГИГАКАЛ/Ч","symbolInternationalView":""},
	{"code":"338","name":"Миллиметр ртутного столба","conventionalNationalView":"мм рт. ст","conventionalInternationalView":"","symbolNationalView":"ММ РТ СТ","symbolInternationalView":""},
	{"code":"337","name":"Миллиметр водяного столба","conventionalNationalView":"мм вод. ст","conventionalInternationalView":"","symbolNationalView":"ММ ВОД СТ","symbolInternationalView":""},
	{"code":"251","name":"Лошадиная сила","conventionalNationalView":"л. с","conventionalInternationalView":"","symbolNationalView":"ЛС","symbolInternationalView":""},
	{"code":"258","name":"Бод","conventionalNationalView":"бод","conventionalInternationalView":"","symbolNationalView":"БОД","symbolInternationalView":""},
	{"code":"242","name":"Миллион киловольт-ампер","conventionalNationalView":"10^6 кВ.А","conventionalInternationalView":"","symbolNationalView":"МЛН КВ.А","symbolInternationalView":""},
	{"code":"232","name":"Килокалория","conventionalNationalView":"ккал","conventionalInternationalView":"","symbolNationalView":"ККАЛ","symbolInternationalView":""},
	{"code":"257","name":"Мегабайт","conventionalNationalView":"Мбайт","conventionalInternationalView":"","symbolNationalView":"МБАЙТ","symbolInternationalView":""},
	{"code":"249","name":"Миллиард киловатт-часов","conventionalNationalView":"10^9 кВт.ч","conventionalInternationalView":"","symbolNationalView":"МЛРД КВТ.Ч","symbolInternationalView":""},
	{"code":"241","name":"Миллион ампер-часов","conventionalNationalView":"10^6 А.ч","conventionalInternationalView":"","symbolNationalView":"МЛН А.Ч","symbolInternationalView":""},
	{"code":"233","name":"Гигакалория","conventionalNationalView":"Гкал","conventionalInternationalView":"","symbolNationalView":"ГИГАКАЛ","symbolInternationalView":""},
	{"code":"253","name":"Миллион лошадиных сил","conventionalNationalView":"10^6 л. с","conventionalInternationalView":"","symbolNationalView":"МЛН ЛС","symbolInternationalView":""},
	{"code":"231","name":"Метр в час","conventionalNationalView":"м/ч","conventionalInternationalView":"","symbolNationalView":"М/Ч","symbolInternationalView":""},
	{"code":"254","name":"Бит","conventionalNationalView":"бит","conventionalInternationalView":"","symbolNationalView":"БИТ","symbolInternationalView":""},
	{"code":"248","name":"Киловольт-ампер реактивный","conventionalNationalView":"кВ.А Р","conventionalInternationalView":"","symbolNationalView":"КВ.А Р","symbolInternationalView":""},
	{"code":"352","name":"Микросекунда","conventionalNationalView":"мкс","conventionalInternationalView":"","symbolNationalView":"МКС","symbolInternationalView":""},
	{"code":"353","name":"Миллисекунда","conventionalNationalView":"млс","conventionalInternationalView":"","symbolNationalView":"МЛС","symbolInternationalView":""},
	{"code":"534","name":"Тонна в час","conventionalNationalView":"т/ч","conventionalInternationalView":"","symbolNationalView":"Т/Ч","symbolInternationalView":""},
	{"code":"513","name":"Автотонна","conventionalNationalView":"авто т","conventionalInternationalView":"","symbolNationalView":"АВТО Т","symbolInternationalView":""},
	{"code":"876","name":"Условная единица","conventionalNationalView":"усл. ед","conventionalInternationalView":"","symbolNationalView":"УСЛ ЕД","symbolInternationalView":""},
	{"code":"918","name":"Лист авторский","conventionalNationalView":"л. авт","conventionalInternationalView":"","symbolNationalView":"ЛИСТ АВТ","symbolInternationalView":""},
	{"code":"873","name":"Тысяча флаконов","conventionalNationalView":"10^3 флак","conventionalInternationalView":"","symbolNationalView":"ТЫС ФЛАК","symbolInternationalView":""},
	{"code":"903","name":"Тысяча ученических мест","conventionalNationalView":"10^3 учен. мест","conventionalInternationalView":"","symbolNationalView":"ТЫС УЧЕН МЕСТ","symbolInternationalView":""},
	{"code":"870","name":"Ампула","conventionalNationalView":"ампул","conventionalInternationalView":"","symbolNationalView":"АМПУЛ","symbolInternationalView":""},
	{"code":"421","name":"Пассажирское место (пассажирских мест)","conventionalNationalView":"пасс. мест","conventionalInternationalView":"","symbolNationalView":"ПАСС МЕСТ","symbolInternationalView":""},
	{"code":"540","name":"Человеко-день","conventionalNationalView":"чел.дн","conventionalInternationalView":"","symbolNationalView":"ЧЕЛ.ДН","symbolInternationalView":""},
	{"code":"427","name":"Пассажиропоток","conventionalNationalView":"пасс.поток","conventionalInternationalView":"","symbolNationalView":"ПАСС.ПОТОК","symbolInternationalView":""},
	{"code":"896","name":"Семья","conventionalNationalView":"семей","conventionalInternationalView":"","symbolNationalView":"СЕМЕЙ","symbolInternationalView":""},
	{"code":"751","name":"Тысяча рулонов","conventionalNationalView":"10^3 рул","conventionalInternationalView":"","symbolNationalView":"ТЫС РУЛ","symbolInternationalView":""},
	{"code":"951","name":"Тысяча вагоно-(машино)-часов","conventionalNationalView":"10^3 ваг (маш).ч","conventionalInternationalView":"","symbolNationalView":"ТЫС ВАГ (МАШ).Ч","symbolInternationalView":""},
	{"code":"963","name":"Приведенный час","conventionalNationalView":"привед.ч","conventionalInternationalView":"","symbolNationalView":"ПРИВЕД.Ч","symbolInternationalView":""},
	{"code":"978","name":"Канало-концы","conventionalNationalView":"канал. конц","conventionalInternationalView":"","symbolNationalView":"КАНАЛ. КОНЦ","symbolInternationalView":""},
	{"code":"975","name":"Суго-сутки","conventionalNationalView":"суго. сут.","conventionalInternationalView":"","symbolNationalView":"СУГО. СУТ","symbolInternationalView":""},
	{"code":"967","name":"Миллион тонно-миль","conventionalNationalView":"10^6 т. миль","conventionalInternationalView":"","symbolNationalView":"МЛН Т. МИЛЬ","symbolInternationalView":""},
	{"code":"792","name":"Человек","conventionalNationalView":"чел","conventionalInternationalView":"","symbolNationalView":"ЧЕЛ","symbolInternationalView":""},
	{"code":"547","name":"Пара в смену","conventionalNationalView":"пар/смен","conventionalInternationalView":"","symbolNationalView":"ПАР/СМЕН","symbolInternationalView":""},
	{"code":"839","name":"Комплект","conventionalNationalView":"компл","conventionalInternationalView":"","symbolNationalView":"КОМПЛ","symbolInternationalView":""},
	{"code":"881","name":"Условная банка","conventionalNationalView":"усл. банк","conventionalInternationalView":"","symbolNationalView":"УСЛ БАНК","symbolInternationalView":""},
	{"code":"562","name":"Тысяча прядильных веретен","conventionalNationalView":"10^3 пряд.верет","conventionalInternationalView":"","symbolNationalView":"ТЫС ПРЯД ВЕРЕТ","symbolInternationalView":""},
	{"code":"909","name":"Квартира","conventionalNationalView":"кварт","conventionalInternationalView":"","symbolNationalView":"КВАРТ","symbolInternationalView":""},
	{"code":"644","name":"Миллион единиц","conventionalNationalView":"10^6 ед","conventionalInternationalView":"","symbolNationalView":"МЛН ЕД","symbolInternationalView":""},
	{"code":"922","name":"Знак","conventionalNationalView":"знак","conventionalInternationalView":"","symbolNationalView":"ЗНАК","symbolInternationalView":""},
	{"code":"877","name":"Тысяча условных единиц","conventionalNationalView":"10^3 усл. ед","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ ЕД","symbolInternationalView":""},
	{"code":"960","name":"Тысяча автомобиле-тонно-дней","conventionalNationalView":"10^3 автомоб.т.дн","conventionalInternationalView":"","symbolNationalView":"ТЫС АВТОМОБ.Т.ДН","symbolInternationalView":""},
	{"code":"954","name":"Вагоно-сутки","conventionalNationalView":"ваг.сут","conventionalInternationalView":"","symbolNationalView":"ВАГ.СУТ","symbolInternationalView":""},
	{"code":"761","name":"Тысяча станов","conventionalNationalView":"10^3 стан","conventionalInternationalView":"","symbolNationalView":"ТЫС СТАН","symbolInternationalView":""},
	{"code":"511","name":"Килограмм на гигакалорию","conventionalNationalView":"кг/Гкал","conventionalInternationalView":"","symbolNationalView":"КГ/ГИГАКАЛ","symbolInternationalView":""},
	{"code":"912","name":"Тысяча коек","conventionalNationalView":"10^3 коек","conventionalInternationalView":"","symbolNationalView":"ТЫС КОЕК","symbolInternationalView":""},
	{"code":"980","name":"Тысяча долларов","conventionalNationalView":"10^3 доллар","conventionalInternationalView":"","symbolNationalView":"ТЫС ДОЛЛАР","symbolInternationalView":""},
	{"code":"387","name":"Триллион рублей","conventionalNationalView":"10^12 руб","conventionalInternationalView":"","symbolNationalView":"ТРИЛЛ РУБ","symbolInternationalView":""},
	{"code":"908","name":"Номер","conventionalNationalView":"ном","conventionalInternationalView":"","symbolNationalView":"НОМ","symbolInternationalView":""},
	{"code":"968","name":"Миллион пассажиро-миль","conventionalNationalView":"10^6 пасс. миль","conventionalInternationalView":"","symbolNationalView":"МЛН ПАСС. МИЛЬ","symbolInternationalView":""},
	{"code":"962","name":"Тысяча автомобиле-место-дней","conventionalNationalView":"10^3 автомоб.мест. дн","conventionalInternationalView":"","symbolNationalView":"ТЫС АВТОМОБ.МЕСТ. ДН","symbolInternationalView":""},
	{"code":"916","name":"Условный ремонт в год","conventionalNationalView":"усл. рем/год","conventionalInternationalView":"","symbolNationalView":"УСЛ РЕМ/ГОД","symbolInternationalView":""},
	{"code":"414","name":"Пассажиро-километр","conventionalNationalView":"пасс.км","conventionalInternationalView":"","symbolNationalView":"ПАСС.КМ","symbolInternationalView":""},
	{"code":"895","name":"Миллион условных кирпичей","conventionalNationalView":"10^6 усл. кирп","conventionalInternationalView":"","symbolNationalView":"МЛН УСЛ КИРП","symbolInternationalView":""},
	{"code":"888","name":"Тысяча условных ящиков","conventionalNationalView":"10^3 усл. ящ","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ ЯЩ","symbolInternationalView":""},
	{"code":"699","name":"Тысяча мест","conventionalNationalView":"10^3 мест","conventionalInternationalView":"","symbolNationalView":"ТЫС МЕСТ","symbolInternationalView":""},
	{"code":"522","name":"Человек на квадратный километр","conventionalNationalView":"чел/км2","conventionalInternationalView":"","symbolNationalView":"ЧЕЛ/КМ2","symbolInternationalView":""},
	{"code":"869","name":"Тысяча бутылок","conventionalNationalView":"10^3 бут","conventionalInternationalView":"","symbolNationalView":"ТЫС БУТ","symbolInternationalView":""},
	{"code":"958","name":"Тысяча пассажиро-миль","conventionalNationalView":"10^3 пасс.миль","conventionalInternationalView":"","symbolNationalView":"ТЫС ПАСС.МИЛЬ","symbolInternationalView":""},
	{"code":"510","name":"Грамм на киловатт-час","conventionalNationalView":"г/кВт.ч","conventionalInternationalView":"","symbolNationalView":"Г/КВТ.Ч","symbolInternationalView":""},
	{"code":"983","name":"Судо-сутки","conventionalNationalView":"суд.сут","conventionalInternationalView":"","symbolNationalView":"СУД.СУТ","symbolInternationalView":""},
	{"code":"535","name":"Тонна в сутки","conventionalNationalView":"т/сут","conventionalInternationalView":"","symbolNationalView":"Т/СУТ","symbolInternationalView":""},
	{"code":"424","name":"Миллион пассажиро-километров","conventionalNationalView":"10^6 пасс. км","conventionalInternationalView":"","symbolNationalView":"МЛН ПАСС.КМ","symbolInternationalView":""},
	{"code":"907","name":"Тысяча посадочных мест","conventionalNationalView":"10^3 посад. мест","conventionalInternationalView":"","symbolNationalView":"ТЫС ПОСАД МЕСТ","symbolInternationalView":""},
	{"code":"965","name":"Тысяча километров","conventionalNationalView":"10^3 км","conventionalInternationalView":"","symbolNationalView":"ТЫС КМ","symbolInternationalView":""},
	{"code":"538","name":"Тысяча тонн в год","conventionalNationalView":"10^3 т/год","conventionalInternationalView":"","symbolNationalView":"ТЫС Т/ГОД","symbolInternationalView":""},
	{"code":"546","name":"Тысяча посещений в смену","conventionalNationalView":"10^3 посещ/смен","conventionalInternationalView":"","symbolNationalView":"ТЫС ПОСЕЩ/ СМЕН","symbolInternationalView":""},
	{"code":"775","name":"Тысяча тюбиков","conventionalNationalView":"10^3 тюбик","conventionalInternationalView":"","symbolNationalView":"ТЫС ТЮБИК","symbolInternationalView":""},
	{"code":"961","name":"Тысяча автомобиле-часов","conventionalNationalView":"10^3 автомоб.ч","conventionalInternationalView":"","symbolNationalView":"ТЫС АВТОМОБ.Ч","symbolInternationalView":""},
	{"code":"537","name":"Тысяча тонн в сезон","conventionalNationalView":"10^3 т/сез","conventionalInternationalView":"","symbolNationalView":"ТЫС Т/СЕЗ","symbolInternationalView":""},
	{"code":"449","name":"Тонно-километр","conventionalNationalView":"т.км","conventionalInternationalView":"","symbolNationalView":"Т.КМ","symbolInternationalView":""},
	{"code":"556","name":"Тысяча голов в год","conventionalNationalView":"10^3 гол/год","conventionalInternationalView":"","symbolNationalView":"ТЫС ГОЛ/ГОД","symbolInternationalView":""},
	{"code":"383","name":"Рубль","conventionalNationalView":"руб","conventionalInternationalView":"","symbolNationalView":"РУБ","symbolInternationalView":""},
	{"code":"970","name":"Миллион пассажиро-место-миль","conventionalNationalView":"10^6 пасс. мест. миль","conventionalInternationalView":"","symbolNationalView":"МЛН ПАСС. МЕСТ. МИЛЬ","symbolInternationalView":""},
	{"code":"921","name":"Лист учетно-издательский","conventionalNationalView":"л. уч.-изд","conventionalInternationalView":"","symbolNationalView":"ЛИСТ УЧ.ИЗД","symbolInternationalView":""},
	{"code":"894","name":"Тысяча условных кирпичей","conventionalNationalView":"10^3 усл. кирп","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ КИРП","symbolInternationalView":""},
	{"code":"514","name":"Тонна тяги","conventionalNationalView":"т.тяги","conventionalInternationalView":"","symbolNationalView":"Т ТЯГИ","symbolInternationalView":""},
	{"code":"388","name":"Квадрильон рублей","conventionalNationalView":"10^15 руб","conventionalInternationalView":"","symbolNationalView":"КВАДР РУБ","symbolInternationalView":""},
	{"code":"541","name":"Тысяча человеко-дней","conventionalNationalView":"10^3 чел.дн","conventionalInternationalView":"","symbolNationalView":"ТЫС ЧЕЛ.ДН","symbolInternationalView":""},
	{"code":"971","name":"Кормо-день","conventionalNationalView":"корм. дн","conventionalInternationalView":"","symbolNationalView":"КОРМ. ДН","symbolInternationalView":""},
	{"code":"953","name":"Тысяча место-километров","conventionalNationalView":"10 ^3мест.км","conventionalInternationalView":"","symbolNationalView":"ТЫС МЕСТ.КМ","symbolInternationalView":""},
	{"code":"871","name":"Тысяча ампул","conventionalNationalView":"10^3 ампул","conventionalInternationalView":"","symbolNationalView":"ТЫС АМПУЛ","symbolInternationalView":""},
	{"code":"385","name":"Миллион рублей","conventionalNationalView":"10^6 руб","conventionalInternationalView":"","symbolNationalView":"МЛН РУБ","symbolInternationalView":""},
	{"code":"966","name":"Тысяча тоннаже-рейсов","conventionalNationalView":"10^3 тоннаж. рейс","conventionalInternationalView":"","symbolNationalView":"ТЫС ТОННАЖ. РЕЙС","symbolInternationalView":""},
	{"code":"911","name":"Койка","conventionalNationalView":"коек","conventionalInternationalView":"","symbolNationalView":"КОЕК","symbolInternationalView":""},
	{"code":"868","name":"Бутылка","conventionalNationalView":"бут","conventionalInternationalView":"","symbolNationalView":"БУТ","symbolInternationalView":""},
	{"code":"892","name":"Тысяча условных плиток","conventionalNationalView":"10^3 усл. плит","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ ПЛИТ","symbolInternationalView":""},
	{"code":"544","name":"Миллион единиц в год","conventionalNationalView":"10^6 ед/год","conventionalInternationalView":"","symbolNationalView":"МЛН ЕД/ГОД","symbolInternationalView":""},
	{"code":"793","name":"Тысяча человек","conventionalNationalView":"10^3 чел","conventionalInternationalView":"","symbolNationalView":"ТЫС ЧЕЛ","symbolInternationalView":""},
	{"code":"949","name":"Миллион листов-оттисков","conventionalNationalView":"10^6 лист.оттиск","conventionalInternationalView":"","symbolNationalView":"МЛН ЛИСТ.ОТТИСК","symbolInternationalView":""},
	{"code":"886","name":"Миллион условных кусков","conventionalNationalView":"10^6 усл. кус","conventionalInternationalView":"","symbolNationalView":"МЛН УСЛ КУС","symbolInternationalView":""},
	{"code":"698","name":"Место","conventionalNationalView":"мест","conventionalInternationalView":"","symbolNationalView":"МЕСТ","symbolInternationalView":""},
	{"code":"536","name":"Тонна в смену","conventionalNationalView":"т/смен","conventionalInternationalView":"","symbolNationalView":"Т/СМЕН","symbolInternationalView":""},
	{"code":"548","name":"Тысяча пар в смену","conventionalNationalView":"10^3 пар/смен","conventionalInternationalView":"","symbolNationalView":"ТЫС ПАР/СМЕН","symbolInternationalView":""},
	{"code":"915","name":"Условный ремонт","conventionalNationalView":"усл. рем","conventionalInternationalView":"","symbolNationalView":"УСЛ РЕМ","symbolInternationalView":""},
	{"code":"812","name":"Ящик","conventionalNationalView":"ящ","conventionalInternationalView":"","symbolNationalView":"ЯЩ","symbolInternationalView":""},
	{"code":"956","name":"Тысяча поездо-километров","conventionalNationalView":"10^3 поезд.км","conventionalInternationalView":"","symbolNationalView":"ТЫС ПОЕЗД.КМ","symbolInternationalView":""},
	{"code":"553","name":"Тысяча тонн переработки в сутки","conventionalNationalView":"10^3 т перераб/ сут","conventionalInternationalView":"","symbolNationalView":"ТЫС Т ПЕРЕРАБ/СУТ","symbolInternationalView":""},
	{"code":"450","name":"Тысяча тонно-километров","conventionalNationalView":"10^3 т.км","conventionalInternationalView":"","symbolNationalView":"ТЫС Т.КМ","symbolInternationalView":""},
	{"code":"950","name":"Вагоно(машино)-день","conventionalNationalView":"ваг (маш).дн","conventionalInternationalView":"","symbolNationalView":"ВАГ (МАШ).ДН","symbolInternationalView":""},
	{"code":"552","name":"Тонна переработки в сутки","conventionalNationalView":"т перераб/сут","conventionalInternationalView":"","symbolNationalView":"Т ПЕРЕРАБ/СУТ","symbolInternationalView":""},
	{"code":"423","name":"Тысяча пассажиро-километров","conventionalNationalView":"10^3 пасс.км","conventionalInternationalView":"","symbolNationalView":"ТЫС ПАСС.КМ","symbolInternationalView":""},
	{"code":"924","name":"Символ","conventionalNationalView":"символ","conventionalInternationalView":"","symbolNationalView":"СИМВОЛ","symbolInternationalView":""},
	{"code":"782","name":"Тысяча упаковок","conventionalNationalView":"10^3 упак","conventionalInternationalView":"","symbolNationalView":"ТЫС УПАК","symbolInternationalView":""},
	{"code":"838","name":"Миллион пар","conventionalNationalView":"10^6 пар","conventionalInternationalView":"","symbolNationalView":"МЛН ПАР","symbolInternationalView":""},
	{"code":"905","name":"Тысяча рабочих мест","conventionalNationalView":"10^3 раб. мест","conventionalInternationalView":"","symbolNationalView":"ТЫС РАБ МЕСТ","symbolInternationalView":""},
	{"code":"887","name":"Условный ящик","conventionalNationalView":"усл. ящ","conventionalInternationalView":"","symbolNationalView":"УСЛ ЯЩ","symbolInternationalView":""},
	{"code":"744","name":"Процент","conventionalNationalView":"%","conventionalInternationalView":"","symbolNationalView":"ПРОЦ","symbolInternationalView":""},
	{"code":"639","name":"Доза","conventionalNationalView":"доз","conventionalInternationalView":"","symbolNationalView":"ДОЗ","symbolInternationalView":""},
	{"code":"891","name":"Условная плитка","conventionalNationalView":"усл. плит","conventionalInternationalView":"","symbolNationalView":"УСЛ ПЛИТ","symbolInternationalView":""},
	{"code":"545","name":"Посещение в смену","conventionalNationalView":"посещ/смен","conventionalInternationalView":"","symbolNationalView":"ПОСЕЩ/СМЕН","symbolInternationalView":""},
	{"code":"543","name":"Тысяча условных банок в смену","conventionalNationalView":"10^3 усл. банк/ смен","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ БАНК/СМЕН","symbolInternationalView":""},
	{"code":"893","name":"Условный кирпич","conventionalNationalView":"усл. кирп","conventionalInternationalView":"","symbolNationalView":"УСЛ КИРП","symbolInternationalView":""},
	{"code":"957","name":"Тысяча тонно-миль","conventionalNationalView":"10^3 т.миль","conventionalInternationalView":"","symbolNationalView":"ТЫС Т.МИЛЬ","symbolInternationalView":""},
	{"code":"977","name":"Канало-километр","conventionalNationalView":"канал. км","conventionalInternationalView":"","symbolNationalView":"КАНАЛ. КМ","symbolInternationalView":""},
	{"code":"901","name":"Миллион домохозяйств","conventionalNationalView":"10^6 домхоз","conventionalInternationalView":"","symbolNationalView":"МЛН ДОМХОЗ","symbolInternationalView":""},
	{"code":"976","name":"Штук в 20-футовом эквиваленте (ДФЭ)","conventionalNationalView":"штук в 20-футовом эквиваленте","conventionalInternationalView":"","symbolNationalView":"ШТ В 20 ФУТ ЭКВИВ","symbolInternationalView":""},
	{"code":"762","name":"Станция","conventionalNationalView":"станц","conventionalInternationalView":"","symbolNationalView":"СТАНЦ","symbolInternationalView":""},
	{"code":"897","name":"Тысяча семей","conventionalNationalView":"10^3 семей","conventionalInternationalView":"","symbolNationalView":"ТЫС СЕМЕЙ","symbolInternationalView":""},
	{"code":"880","name":"Тысяча условных штук","conventionalNationalView":"10^3 усл. шт","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ ШТ","symbolInternationalView":""},
	{"code":"923","name":"Слово","conventionalNationalView":"слово","conventionalInternationalView":"","symbolNationalView":"СЛОВО","symbolInternationalView":""},
	{"code":"955","name":"Тысяча поездо-часов","conventionalNationalView":"10^3 поезд.ч","conventionalInternationalView":"","symbolNationalView":"ТЫС ПОЕЗД.Ч","symbolInternationalView":""},
	{"code":"539","name":"Человеко-час","conventionalNationalView":"чел.ч","conventionalInternationalView":"","symbolNationalView":"ЧЕЛ.Ч","symbolInternationalView":""},
	{"code":"661","name":"Канал","conventionalNationalView":"канал","conventionalInternationalView":"","symbolNationalView":"КАНАЛ","symbolInternationalView":""},
	{"code":"874","name":"Тысяча тубов","conventionalNationalView":"10^3 туб","conventionalInternationalView":"","symbolNationalView":"ТЫС ТУБ","symbolInternationalView":""},
	{"code":"558","name":"Тысяча птицемест","conventionalNationalView":"10^3 птицемест","conventionalInternationalView":"","symbolNationalView":"ТЫС ПТИЦЕМЕСТ","symbolInternationalView":""},
	{"code":"913","name":"Том книжного фонда","conventionalNationalView":"том книжн. фонд","conventionalInternationalView":"","symbolNationalView":"ТОМ КНИЖН ФОНД","symbolInternationalView":""},
	{"code":"673","name":"Тысяча комплектов","conventionalNationalView":"10^3 компл","conventionalInternationalView":"","symbolNationalView":"ТЫС КОМПЛ","symbolInternationalView":""},
	{"code":"640","name":"Тысяча доз","conventionalNationalView":"10^3 доз","conventionalInternationalView":"","symbolNationalView":"ТЫС ДОЗ","symbolInternationalView":""},
	{"code":"643","name":"Тысяча единиц","conventionalNationalView":"10^3 ед","conventionalInternationalView":"","symbolNationalView":"ТЫС ЕД","symbolInternationalView":""},
	{"code":"878","name":"Миллион условных единиц","conventionalNationalView":"10^6 усл. ед","conventionalInternationalView":"","symbolNationalView":"МЛН УСЛ ЕД","symbolInternationalView":""},
	{"code":"914","name":"Тысяча томов книжного фонда","conventionalNationalView":"10^3 том. книжн. фонд","conventionalInternationalView":"","symbolNationalView":"ТЫС ТОМ КНИЖН ФОНД","symbolInternationalView":""},
	{"code":"883","name":"Миллион условных банок","conventionalNationalView":"10^6 усл. банк","conventionalInternationalView":"","symbolNationalView":"МЛН УСЛ БАНК","symbolInternationalView":""},
	{"code":"384","name":"Тысяча рублей","conventionalNationalView":"10^3 руб","conventionalInternationalView":"","symbolNationalView":"ТЫС РУБ","symbolInternationalView":""},
	{"code":"889","name":"Условная катушка","conventionalNationalView":"усл. кат","conventionalInternationalView":"","symbolNationalView":"УСЛ КАТ","symbolInternationalView":""},
	{"code":"925","name":"Условная труба","conventionalNationalView":"усл. труб","conventionalInternationalView":"","symbolNationalView":"УСЛ ТРУБ","symbolInternationalView":""},
	{"code":"900","name":"Тысяча домохозяйств","conventionalNationalView":"10^3 домхоз","conventionalInternationalView":"","symbolNationalView":"ТЫС ДОМХОЗ","symbolInternationalView":""},
	{"code":"898","name":"Миллион семей","conventionalNationalView":"10^6 семей","conventionalInternationalView":"","symbolNationalView":"МЛН СЕМЕЙ","symbolInternationalView":""},
	{"code":"964","name":"Самолето-километр","conventionalNationalView":"самолет.км","conventionalInternationalView":"","symbolNationalView":"САМОЛЕТ.КМ","symbolInternationalView":""},
	{"code":"979","name":"Тысяча экземпляров","conventionalNationalView":"10^3 экз","conventionalInternationalView":"","symbolNationalView":"ТЫС ЭКЗ","symbolInternationalView":""},
	{"code":"746","name":"Промилле (0,1 процента)","conventionalNationalView":"промилле","conventionalInternationalView":"","symbolNationalView":"ПРОМИЛЛЕ","symbolInternationalView":""},
	{"code":"890","name":"Тысяча условных катушек","conventionalNationalView":"10^3 усл. кат","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ КАТ","symbolInternationalView":""},
	{"code":"724","name":"Тысяча гектаров порций","conventionalNationalView":"10^3 га порц","conventionalInternationalView":"","symbolNationalView":"ТЫС ГА ПОРЦ","symbolInternationalView":""},
	{"code":"542","name":"Тысяча человеко-часов","conventionalNationalView":"10^3 чел.ч","conventionalInternationalView":"","symbolNationalView":"ТЫС ЧЕЛ.Ч","symbolInternationalView":""},
	{"code":"642","name":"Единица","conventionalNationalView":"ед","conventionalInternationalView":"","symbolNationalView":"ЕД","symbolInternationalView":""},
	{"code":"560","name":"Минимальная заработная плата","conventionalNationalView":"мин. заработн. плат","conventionalInternationalView":"","symbolNationalView":"МИН ЗАРАБОТН ПЛАТ","symbolInternationalView":""},
	{"code":"557","name":"Миллион голов в год","conventionalNationalView":"10^6 гол/год","conventionalInternationalView":"","symbolNationalView":"МЛН ГОЛ/ГОД","symbolInternationalView":""},
	{"code":"917","name":"Смена","conventionalNationalView":"смен","conventionalInternationalView":"","symbolNationalView":"СМЕН","symbolInternationalView":""},
	{"code":"902","name":"Ученическое место","conventionalNationalView":"учен. мест","conventionalInternationalView":"","symbolNationalView":"УЧЕН МЕСТ","symbolInternationalView":""},
	{"code":"521","name":"Человек на квадратный метр","conventionalNationalView":"чел/м2","conventionalInternationalView":"","symbolNationalView":"ЧЕЛ/М2","symbolInternationalView":""},
	{"code":"479","name":"Тысяча наборов","conventionalNationalView":"10^3 набор","conventionalInternationalView":"","symbolNationalView":"ТЫС НАБОР","symbolInternationalView":""},
	{"code":"899","name":"Домохозяйство","conventionalNationalView":"домхоз","conventionalInternationalView":"","symbolNationalView":"ДОМХОЗ","symbolInternationalView":""},
	{"code":"906","name":"Посадочное место","conventionalNationalView":"посад. мест","conventionalInternationalView":"","symbolNationalView":"ПОСАД МЕСТ","symbolInternationalView":""},
	{"code":"982","name":"Миллион тонн кормовых единиц","conventionalNationalView":"10^6 корм ед","conventionalInternationalView":"","symbolNationalView":"МЛН Т КОРМ ЕД","symbolInternationalView":""},
	{"code":"515","name":"Дедвейт-тонна","conventionalNationalView":"дедвейт.т","conventionalInternationalView":"","symbolNationalView":"ДЕДВЕЙТ.Т","symbolInternationalView":""},
	{"code":"959","name":"Автомобиле-день","conventionalNationalView":"автомоб.дн","conventionalInternationalView":"","symbolNationalView":"АВТОМОБ.ДН","symbolInternationalView":""},
	{"code":"972","name":"Центнер кормовых единиц","conventionalNationalView":"ц корм ед","conventionalInternationalView":"","symbolNationalView":"Ц КОРМ ЕД","symbolInternationalView":""},
	{"code":"882","name":"Тысяча условных банок","conventionalNationalView":"10^3 усл. банк","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ БАНК","symbolInternationalView":""},
	{"code":"969","name":"Миллион тоннаже-миль","conventionalNationalView":"10^6 тоннаж. миль","conventionalInternationalView":"","symbolNationalView":"МЛН ТОННАЖ. МИЛЬ","symbolInternationalView":""},
	{"code":"837","name":"Тысяча пар","conventionalNationalView":"10^3 пар","conventionalInternationalView":"","symbolNationalView":"ТЫС ПАР","symbolInternationalView":""},
	{"code":"810","name":"Ячейка","conventionalNationalView":"яч","conventionalInternationalView":"","symbolNationalView":"ЯЧ","symbolInternationalView":""},
	{"code":"516","name":"Тонно-танид","conventionalNationalView":"т.танид","conventionalInternationalView":"","symbolNationalView":"Т.ТАНИД","symbolInternationalView":""},
	{"code":"794","name":"Миллион человек","conventionalNationalView":"10^6 чел","conventionalInternationalView":"","symbolNationalView":"МЛН ЧЕЛ","symbolInternationalView":""},
	{"code":"451","name":"Миллион тонно-километров","conventionalNationalView":"10^6 т. км","conventionalInternationalView":"","symbolNationalView":"МЛН Т.КМ","symbolInternationalView":""},
	{"code":"836","name":"Голова","conventionalNationalView":"гол","conventionalInternationalView":"","symbolNationalView":"ГОЛ","symbolInternationalView":""},
	{"code":"872","name":"Флакон","conventionalNationalView":"флак","conventionalInternationalView":"","symbolNationalView":"ФЛАК","symbolInternationalView":""},
	{"code":"808","name":"Миллион экземпляров","conventionalNationalView":"10^6 экз","conventionalInternationalView":"","symbolNationalView":"МЛН ЭКЗ","symbolInternationalView":""},
	{"code":"561","name":"Тысяча тонн пара в час","conventionalNationalView":"10^3 т пар/ч","conventionalInternationalView":"","symbolNationalView":"ТЫС Т ПАР/Ч","symbolInternationalView":""},
	{"code":"973","name":"Тысяча автомобиле-километров","conventionalNationalView":"10^3 автомоб. км","conventionalInternationalView":"","symbolNationalView":"ТЫС АВТОМОБ. КМ","symbolInternationalView":""},
	{"code":"981","name":"Тысяча тонн кормовых единиц","conventionalNationalView":"10^3 корм ед","conventionalInternationalView":"","symbolNationalView":"ТЫС Т КОРМ ЕД","symbolInternationalView":""},
	{"code":"386","name":"Миллиард рублей","conventionalNationalView":"10^9 руб","conventionalInternationalView":"","symbolNationalView":"МЛРД РУБ","symbolInternationalView":""},
	{"code":"554","name":"Центнер переработки в сутки","conventionalNationalView":"ц перераб/сут","conventionalInternationalView":"","symbolNationalView":"Ц ПЕРЕРАБ/СУТ","symbolInternationalView":""},
	{"code":"885","name":"Тысяча условных кусков","conventionalNationalView":"10^3 усл. кус","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ КУС","symbolInternationalView":""},
	{"code":"937","name":"Миллион доз","conventionalNationalView":"10^6 доз","conventionalInternationalView":"","symbolNationalView":"МЛН ДОЗ","symbolInternationalView":""},
	{"code":"920","name":"Лист печатный","conventionalNationalView":"л. печ","conventionalInternationalView":"","symbolNationalView":"ЛИСТ ПЕЧ","symbolInternationalView":""},
	{"code":"779","name":"Миллион упаковок","conventionalNationalView":"10^6 упак","conventionalInternationalView":"","symbolNationalView":"МЛН УПАК","symbolInternationalView":""},
	{"code":"709","name":"Тысяча номеров","conventionalNationalView":"10^3 ном","conventionalInternationalView":"","symbolNationalView":"ТЫС НОМ","symbolInternationalView":""},
	{"code":"512","name":"Тонно-номер","conventionalNationalView":"т.ном","conventionalInternationalView":"","symbolNationalView":"Т.НОМ","symbolInternationalView":""},
	{"code":"952","name":"Тысяча вагоно-(машино)-километров","conventionalNationalView":"10^3 ваг (маш).км","conventionalInternationalView":"","symbolNationalView":"ТЫС ВАГ (МАШ).КМ","symbolInternationalView":""},
	{"code":"879","name":"Условная штука","conventionalNationalView":"усл. шт","conventionalInternationalView":"","symbolNationalView":"УСЛ ШТ","symbolInternationalView":""},
	{"code":"904","name":"Рабочее место","conventionalNationalView":"раб. мест","conventionalInternationalView":"","symbolNationalView":"РАБ МЕСТ","symbolInternationalView":""},
	{"code":"559","name":"Тысяча кур-несушек","conventionalNationalView":"10^3 кур. несуш","conventionalInternationalView":"","symbolNationalView":"ТЫС КУР. НЕСУШ","symbolInternationalView":""},
	{"code":"840","name":"Секция","conventionalNationalView":"секц","conventionalInternationalView":"","symbolNationalView":"СЕКЦ","symbolInternationalView":""},
	{"code":"974","name":"Тысяча тоннаже-сут","conventionalNationalView":"10^3 тоннаж. сут","conventionalInternationalView":"","symbolNationalView":"ТЫС ТОННАЖ. СУТ","symbolInternationalView":""},
	{"code":"729","name":"Тысяча пачек","conventionalNationalView":"10^3 пач","conventionalInternationalView":"","symbolNationalView":"ТЫС ПАЧ","symbolInternationalView":""},
	{"code":"910","name":"Тысяча квартир","conventionalNationalView":"10^3 кварт","conventionalInternationalView":"","symbolNationalView":"ТЫС КВАРТ","symbolInternationalView":""},
	{"code":"550","name":"Миллион тонн в год","conventionalNationalView":"10^6 т/год","conventionalInternationalView":"","symbolNationalView":"МЛН Т/ГОД","symbolInternationalView":""},
	{"code":"563","name":"Тысяча прядильных мест","conventionalNationalView":"10^3 пряд.мест","conventionalInternationalView":"","symbolNationalView":"ТЫС ПРЯД МЕСТ","symbolInternationalView":""},
	{"code":"875","name":"Тысяча коробок","conventionalNationalView":"10^3 кор","conventionalInternationalView":"","symbolNationalView":"ТЫС КОР","symbolInternationalView":""},
	{"code":"776","name":"Тысяча условных тубов","conventionalNationalView":"10^3 усл.туб","conventionalInternationalView":"","symbolNationalView":"ТЫС УСЛ ТУБ","symbolInternationalView":""},
	{"code":"884","name":"Условный кусок","conventionalNationalView":"усл. кус","conventionalInternationalView":"","symbolNationalView":"УСЛ КУС","symbolInternationalView":""},
	{"code":"930","name":"Тысяча пластин","conventionalNationalView":"10^3 пласт","conventionalInternationalView":"","symbolNationalView":"ТЫС ПЛАСТ","symbolInternationalView":""},
	{"code":"555","name":"Тысяча центнеров переработки в сутки","conventionalNationalView":"10^3 ц перераб/ сут","conventionalInternationalView":"","symbolNationalView":"ТЫС Ц ПЕРЕРАБ/СУТ","symbolInternationalView":""},
	{"code":"017","name":"Гектометр","conventionalNationalView":"","conventionalInternationalView":"hm","symbolNationalView":"","symbolInternationalView":"HMT"},
	{"code":"045","name":"Миля (уставная) (1609,344 м)","conventionalNationalView":"","conventionalInternationalView":"mile","symbolNationalView":"","symbolInternationalView":"SMI"},
	{"code":"079","name":"Квадратная миля","conventionalNationalView":"","conventionalInternationalView":"mile2","symbolNationalView":"","symbolInternationalView":"MIK"},
	{"code":"077","name":"Акр (4840 квадратных ярдов)","conventionalNationalView":"","conventionalInternationalView":"acre","symbolNationalView":"","symbolInternationalView":"ACR"},
	{"code":"137","name":"Пинта СК (0,568262 дм3)","conventionalNationalView":"","conventionalInternationalView":"pt (UK)","symbolNationalView":"","symbolInternationalView":"PTI"},
	{"code":"141","name":"Жидкостная унция США (29,5735 см3)","conventionalNationalView":"","conventionalInternationalView":"fl oz (US)","symbolNationalView":"","symbolInternationalView":"OZA"},
	{"code":"149","name":"Сухой галлон США (4,404884 дм3)","conventionalNationalView":"","conventionalInternationalView":"dry gal (US)","symbolNationalView":"","symbolInternationalView":"GLD"},
	{"code":"153","name":"Корд (3,63 м3)","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"WCD"},
	{"code":"152","name":"Стандарт","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"WSD"},
	{"code":"145","name":"Жидкостный галлон США (3,78541 дм3)","conventionalNationalView":"","conventionalInternationalView":"gal (US)","symbolNationalView":"","symbolInternationalView":"GLL"},
	{"code":"154","name":"Тысячи бордфутов (2,36 м3)","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"MBF"},
	{"code":"143","name":"Жидкостная пинта США (0,473176 дм3)","conventionalNationalView":"","conventionalInternationalView":"liq pt (US)","symbolNationalView":"","symbolInternationalView":"PTL"},
	{"code":"150","name":"Бушель США (35,2391 дм3)","conventionalNationalView":"","conventionalInternationalView":"bu (US)","symbolNationalView":"","symbolInternationalView":"BUA"},
	{"code":"136","name":"Джилл СК (0,142065 дм3)","conventionalNationalView":"","conventionalInternationalView":"gill (UK)","symbolNationalView":"","symbolInternationalView":"GII"},
	{"code":"144","name":"Жидкостная кварта США (0,946353 дм3)","conventionalNationalView":"","conventionalInternationalView":"liq qt (US)","symbolNationalView":"","symbolInternationalView":"QTL"},
	{"code":"138","name":"Кварта СК (1,136523 дм3)","conventionalNationalView":"","conventionalInternationalView":"qt (UK)","symbolNationalView":"","symbolInternationalView":"QTI"},
	{"code":"135","name":"Жидкостная унция СК (28,413 см3)","conventionalNationalView":"","conventionalInternationalView":"fl oz (UK)","symbolNationalView":"","symbolInternationalView":"OZI"},
	{"code":"139","name":"Галлон СК (4,546092 дм3)","conventionalNationalView":"","conventionalInternationalView":"gal (UK)","symbolNationalView":"","symbolInternationalView":"GLI"},
	{"code":"148","name":"Сухая кварта США (1,101221 дм3)","conventionalNationalView":"","conventionalInternationalView":"dry qt (US)","symbolNationalView":"","symbolInternationalView":"QTD"},
	{"code":"140","name":"Бушель СК (36,36874 дм3)","conventionalNationalView":"","conventionalInternationalView":"bu (UK)","symbolNationalView":"","symbolInternationalView":"BUI"},
	{"code":"151","name":"Сухой баррель США (115,627 дм3)","conventionalNationalView":"","conventionalInternationalView":"bbl (US)","symbolNationalView":"","symbolInternationalView":"BLD"},
	{"code":"142","name":"Джилл США (11,8294 см3)","conventionalNationalView":"","conventionalInternationalView":"gill (US)","symbolNationalView":"","symbolInternationalView":"GIA"},
	{"code":"147","name":"Сухая пинта США (0,55061 дм3)","conventionalNationalView":"","conventionalInternationalView":"dry pt (US)","symbolNationalView":"","symbolInternationalView":"PTD"},
	{"code":"146","name":"Баррель (нефтяной) США (158,987 дм3)","conventionalNationalView":"","conventionalInternationalView":"barrel (US)","symbolNationalView":"","symbolInternationalView":"BLL"},
	{"code":"184","name":"Водоизмещение","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"DPT"},
	{"code":"193","name":"Центнер США (45,3592 кг)","conventionalNationalView":"","conventionalInternationalView":"cwt","symbolNationalView":"","symbolInternationalView":"CWA"},
	{"code":"190","name":"Стоун СК (6,350293 кг)","conventionalNationalView":"","conventionalInternationalView":"st","symbolNationalView":"","symbolInternationalView":"STI"},
	{"code":"189","name":"Гран СК, США (64,798910 мг)","conventionalNationalView":"","conventionalInternationalView":"gn","symbolNationalView":"","symbolInternationalView":"GRN"},
	{"code":"200","name":"Драхма США (3,887935 г)","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"DRA"},
	{"code":"194","name":"Длинный центнер СК (50,802345 кг)","conventionalNationalView":"","conventionalInternationalView":"cwt (UK)","symbolNationalView":"","symbolInternationalView":"CWI"},
	{"code":"191","name":"Квартер СК (12,700586 кг)","conventionalNationalView":"","conventionalInternationalView":"qtr","symbolNationalView":"","symbolInternationalView":"QTR"},
	{"code":"186","name":"Фунт СК, США (0,45359237 кг)","conventionalNationalView":"","conventionalInternationalView":"lb","symbolNationalView":"","symbolInternationalView":"LBR"},
	{"code":"187","name":"Унция СК, США (28,349523 г)","conventionalNationalView":"","conventionalInternationalView":"oz","symbolNationalView":"","symbolInternationalView":"ONZ"},
	{"code":"197","name":"Скрупул СК, США (1,295982 г)","conventionalNationalView":"","conventionalInternationalView":"scr","symbolNationalView":"","symbolInternationalView":"SCR"},
	{"code":"182","name":"Нетто-регистровая тонна","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"NTT"},
	{"code":"202","name":"Тройский фунт США (373,242 г)","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"LBT"},
	{"code":"201","name":"Унция СК, США (31,10348 г); тройская унция","conventionalNationalView":"","conventionalInternationalView":"apoz","symbolNationalView":"","symbolInternationalView":"APZ"},
	{"code":"196","name":"Длинная тонна СК, США (1,0160469 т) [2*]","conventionalNationalView":"","conventionalInternationalView":"lt","symbolNationalView":"","symbolInternationalView":"LTN"},
	{"code":"188","name":"Драхма СК (1,771745 г)","conventionalNationalView":"","conventionalInternationalView":"dr","symbolNationalView":"","symbolInternationalView":"DRI"},
	{"code":"183","name":"Обмерная (фрахтовая) тонна","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"SHT"},
	{"code":"198","name":"Пеннивейт СК, США (1,555174 г)","conventionalNationalView":"","conventionalInternationalView":"dwt","symbolNationalView":"","symbolInternationalView":"DWT"},
	{"code":"192","name":"Центал СК (45,359237 кг)","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"CNT"},
	{"code":"195","name":"Короткая тонна СК, США (0,90718474 т) [2*]","conventionalNationalView":"","conventionalInternationalView":"sht","symbolNationalView":"","symbolInternationalView":"STN"},
	{"code":"199","name":"Драхма СК (3,887935 г)","conventionalNationalView":"","conventionalInternationalView":"drm","symbolNationalView":"","symbolInternationalView":"DRM"},
	{"code":"275","name":"Британская тепловая единица (1,055 кДж)","conventionalNationalView":"","conventionalInternationalView":"Btu","symbolNationalView":"","symbolInternationalView":"BTU"},
	{"code":"213","name":"Эффективная мощность (245,7 ватт)","conventionalNationalView":"","conventionalInternationalView":"B.h.p.","symbolNationalView":"","symbolInternationalView":"BHP"},
	{"code":"638","name":"Гросс (144 шт.)","conventionalNationalView":"","conventionalInternationalView":"gr; 144","symbolNationalView":"","symbolInternationalView":"GRO"},
	{"code":"853","name":"Сто международных единиц","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"HIU"},
	{"code":"835","name":"Галлон спирта установленной крепости","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"PGL"},
	{"code":"851","name":"Международная единица","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"NIU"},
	{"code":"731","name":"Большой гросс (12 гроссов)","conventionalNationalView":"","conventionalInternationalView":"1728","symbolNationalView":"","symbolInternationalView":"GGR"},
	{"code":"738","name":"Короткий стандарт (7200 единиц)","conventionalNationalView":"","conventionalInternationalView":"","symbolNationalView":"","symbolInternationalView":"SST"},
]

const MapData = new Map()
SourceData.forEach((unit) => {
	MapData.set(unit.code, unit)
})

module.exports = {
	get: (code) => {return MapData.get(code)},
	has: (code) => {return MapData.has(code)},
	store: () => {return JSON.parse(JSON.stringify(SourceData))},
}
